### ISSUE TITLE
Error viewing Cucumber-JVM .json reports when using Scenario Outline in Cucumber/Ruby

### ISSUE THREAD

**Issue by maddyjakk** [jenkinsci/cucumber-reports-plugin#107]
Hi,

I use Cucumber+Ruby framework to execute tests and generate .html and .json reports. I'm using Jenkins Cucumber-JVM plugin to view the results/graphs generated out of the cucumber.json report.

For features with Scenario Outlines, I get the following error. Is there a way to work around the issue? (I can email the .json file if needed)
java.lang.NullPointerException
at net.masterthought.cucumber.json.Element.calculateStatus(Element.java:146)
at net.masterthought.cucumber.json.Element.setMetaData(Element.java:128)
at net.masterthought.cucumber.json.Feature.setMetaData(Feature.java:151)
at net.masterthought.cucumber.ReportParser.setMetadata(ReportParser.java:91)
at net.masterthought.cucumber.ReportParser.parseJsonResults(ReportParser.java:61)
at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:56)
at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:125)
at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:70)
at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
at hudson.model.Build$BuildExecution.post2(Build.java:185)
at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
at hudson.model.Run.execute(Run.java:1745)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:410)

Trying to generate report from following files. Make sure they are valid cucumber report files:
/var/lib/jenkins/jobs/regression/builds/131/cucumber20161221-154148.json

The broken .json reports cause Jenkins builds to break even though all the tests are successful and don't offer a way to view the results in the event .html results are unavailable to be mailed out via Jenkins Server.

Environment:

Version used: Ruby 2.3.0, cucumber: 2.0.0
Operating System and version: RHEL7
Appreciate any support!

**Comment by damianszczepanik** [comment]
Attach json file

**Comment by maddyjakk** [comment]
.json attached (uploading attachement as a.txt as .json format isn't supported)
[cucumber20161222-130137.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/669467/cucumber20161222-130137.txt)

**Comment by damianszczepanik** [comment]
The problem is that your steps (some) don't have section with result https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/test/resources/json/simple.json#L11

And the question is: why some of them have, other don't?

**Comment by maddyjakk** [comment]
Attached is the corresponding html report file that was generated and the html file shows up fine. The steps are all structured the same way. You can take a look at the scenarios as well. Let me know if you would need the .rb file as well.
[results_smoke20161222-130137.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/671207/results_smoke20161222-130137.txt)

**Comment by damianszczepanik** [comment]
Again, I think that the report is not valid but I'm not sure where is the source of the problem. Step without result is like test without assertion - you don't know if the step has ended with success of failure.

Thus I don't think this is a report bug.
