### ISSUE TITLE
IllegalStateException exception on projects having a space in the Job name

### ISSUE THREAD

**Issue by ajbanck** [jenkinsci/cucumber-reports-plugin#11]
After updating the Cucumber Reports Plugin from 0.1.0 to 1.0.0 reports no longer work for projects that have a space in the name.
Hinted by the error message using unescaped path as /My Test/ I tried replacing the spaces with underscores and that indeed resolved the problem. Reporting worked with jobs having spaces in older versions

The error message (if any) is below:

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.Gson.fromJson(Gson.java:873)
	at com.google.gson.Gson.fromJson(Gson.java:799)
	at net.masterthought.cucumber.ReportParser.parseJsonResults(ReportParser.java:27)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:146)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:137)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:351)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
	at com.google.gson.Gson.fromJson(Gson.java:861)
	... 13 more

Trying to generate report from following files. 
Make sure they are valid cucumber report files: 
/var/lib/jenkins/jobs/My Test/builds/22/cucumber-html-reports/functional/smoketest/target/cucumber.json

**Comment by damianszczepanik** [comment]
That errors means that json file is not valid and it says where. Check if you are not trying to parse json file which is not cucumber report.

If you don't agree reopen and attach json report :)
