### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.commons.lang3.math.NumberUtils

### ISSUE THREAD

**Issue by matthiasbaldi** [jenkinsci/cucumber-reports-plugin#111]
I think the following Error is a bug in the actual (3.4.0) cucumber-reports plugin.
After I couldn't find an other solution, I downgraded to the plugin version 3.3.0 and it works now.
We are running a Jenkins on version 2.36.

**Error Message:**
`java.lang.NoSuchMethodError: org.apache.commons.lang3.math.NumberUtils.isCreatable(Ljava/lang/String;)Z
	at net.masterthought.cucumber.generators.AbstractPage.buildGeneralParameters(AbstractPage.java:109)
	at net.masterthought.cucumber.generators.AbstractPage.<init>(AbstractPage.java:52)
	at net.masterthought.cucumber.generators.FeaturesOverviewPage.<init>(FeaturesOverviewPage.java:12)
	at net.masterthought.cucumber.ReportBuilder.collectPages(ReportBuilder.java:126)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:79)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:123)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:73)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1067)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1754)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:544)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)`

**Comment by damianszczepanik** [comment]
Attach json file so I can take a look

**Comment by matthiasbaldi** [comment]
@damianszczepanik 
Thank you for your answer.
We investigated more in our environment and found a possible error in interaction with other plugins or our Jenkins configuration.
Because in an empty and fresh installed Jenkins 2.36 we could use the cucumber plugin 3.4.0 without any problems or errors logs.
But we couln't found the guilty plugin or configuration of Jenkins.
Actually we can work with the older version of the cucumber plugin (3.3.0). And in the future we have to cleanup our plugins and the Jenkins configuration.
So anyway, I think this "issue" isn't one for other peoples. I will close it.

**Comment by balukondamuri** [comment]
@damianszczepanik Hello Sir, I am able to see the below when executing my program.

java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.copyInputStreamToFile(Ljava/io/InputStream;Ljava/io/File;)V
	at net.masterthought.cucumber.ReportBuilder.copyResources(ReportBuilder.java:139)
	at net.masterthought.cucumber.ReportBuilder.copyStaticResources(ReportBuilder.java:118)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:80)
	at com.premierinc.pcops.testsuite.behavior.cucumber.steps.CommonCucumberSteps.sendReport(CommonCucumberSteps.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)

**Comment by guptaakhil** [comment]
Hi, 

I am getting this very long time. Please do let me know if this issue is resolved now

**Comment by ransom4real** [comment]
Any updates with this issue? I am noticing it on Jenkins 2.131 running on CentOS using cucumber reports 3.18.0

All efforts to fix this issue has proven futile. I have jenkins running on a Mac OSX host and cucumber reports seem to work. This is very strange as it happened out of nowhere. Any help will be appreciated around this please.

**Comment by damianszczepanik** [comment]
It was fixed so if this still happens, more details must be provided to reproduce the problem again
