### ISSUE TITLE
NPE at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:133)

### ISSUE THREAD

**Issue by ostov** [jenkinsci/cucumber-reports-plugin#119]
Jenkins ver. 2.46
Cucumber reports 3.5.0

```[CucumberReport] Preparing Cucumber Reports
[CucumberReport] Copied 4 json files from workspace "/home/jenkins/workspace/mercury/target" to reports directory "/home/jenkins/jenkins_home/jobs/mercury/builds/124/cucumber-html-reports/.cache"
[CucumberReport] Filtered out 1 json files:
[CucumberReport] /home/jenkins/jenkins_home/jobs/mercury/builds/124/cucumber-html-reports/.cache/cucumber.json
ERROR: Build step failed with exception
java.lang.NullPointerException
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:133)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:86)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1067)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:544)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)```

**Comment by ostov** [comment]
I have managed to resolve this issue by changing Report Path from "target" to "target/."
But this is odd.

**Comment by choppedpork** [comment]
Having a similar (the same?) issue since upgrading to 3.5.0 - in a traditional Maven project I've not got the Report Path set at all, the error is:
```
java.lang.NullPointerException
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:133)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:86)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1067)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:544)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
```

From a pipeline build I'm getting a very similar NPE (not identical though). Weirdly enough the error is not in the Jenkins job log but inside of the cucumber report!
![screenshot from 2017-02-14 20-16-49](https://cloud.githubusercontent.com/assets/11997044/22947352/96775484-f2f2-11e6-9962-2bb859452f43.png)

**Comment by damianszczepanik** [comment]
Show me JSON file

**Comment by rkettelerij** [comment]
We're experiencing the same issue:

```
12:02:27 ERROR: Build step failed with exception
12:02:27 java.lang.NullPointerException
12:02:27 	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:133)
12:02:27 	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:86)
12:02:27 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
12:02:27 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
12:02:27 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
12:02:27 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
12:02:27 	at hudson.model.Build$BuildExecution.post2(Build.java:185)
12:02:27 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
12:02:27 	at hudson.model.Run.execute(Run.java:1753)
12:02:27 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:02:27 	at hudson.model.ResourceController.execute(ResourceController.java:98)
12:02:27 	at hudson.model.Executor.run(Executor.java:404)
```

Downgrading from 3.5 to 3.4 solved the issue.

**Comment by damianszczepanik** [comment]
OK, i'm not sure why it happens but I know how to fix it. Will be in next release.

In the meantime the workaround is to just edit job configuration and save it again - then it will probably save empty collection, not null reference

**Comment by damianszczepanik** [comment]
Released
