### ISSUE TITLE
Missing report result - report was not successfully completed

### ISSUE THREAD

**Issue by kalyanhi** [jenkinsci/cucumber-reports-plugin#150]
I have been using Cucumber Reports plugin for my Cucumber - Ruby automation and getting reports. 
Earlier we were getting below information (successfully creating reports)
3 scenarios (3 passed)
12 steps (12 passed)
0m13.712s
[CucumberReport] Preparing Cucumber Reports
[CucumberReport] Copied 11 json files from "C:\Jenkins\workspace\cucumber_tests" to reports directory "C:\Jenkins\jobs\cucumber_tests\builds\140"
[CucumberReport] Found 1 json files.
Finished: SUCCESS
============
But now (Failure)gettingfollowing detials end of the job in jenkins. 
6 scenarios (6 passed)
18 steps (18 passed)
0m48.055s

[CucumberReport] Preparing Cucumber Reports
[CucumberReport] Copied 1 json files from workspace "C:\Jenkins\workspace\cucumber_tests" to reports directory "C:\Jenkins\jobs\cucumber_tests\builds\171\cucumber-html-reports\.cache"
[CucumberReport] Processing 1 json files:
[CucumberReport] C:\Jenkins\jobs\cucumber_tests\builds\171\cucumber-html-reports\.cache\ECIF_Automation\report.json
[CucumberReport] Missing report result - report was not successfully completed
[CucumberReport] Build status is left unchanged
Finished: SUCCESS
Getting error message when I clicked on the cucumber reports link on the each build
net.masterthought.cucumber.ValidationException: File 'C:\Jenkins\jobs\cucumber_tests\builds\171\cucumber-html-reports\.cache\ECIF_Automation\report.json' is not proper Cucumber report!
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:87)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:58)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:86)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:166)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:108)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:401)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: java.io.InputStreamReader@7d2525; line: 1, column: 795] (through reference chain: java.lang.Object[][0]->net.masterthought.cucumber.json.Feature["elements"]->java.lang.Object[][0]->net.masterthought.cucumber.json.Element["before"]->java.lang.Object[][0]->net.masterthought.cucumber.json.Hook["match"]->net.masterthought.cucumber.json.Match["location"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:60)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2887)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:81)

Please find below report.json file content
[{"uri":"features/scenarios/rest_services/getcustomer_patchcustomer.feature","id":"testing-the-patchcustomer-and-getcustomer-rest-services","keyword":"Feature","name":"Testing the patchCustomer and GetCustomer REST services","description":"","line":3,"tags":[{"name":"@rest_regression","line":1},{"name":"@PC","line":1},{"name":"@GC","line":1}],"elements":[{"id":"testing-the-patchcustomer-and-getcustomer-rest-services;validating-patchcustomer-updates-language-options-and-getcustomer-retrieves-them;;2","keyword":"Scenario Outline","name":"Validating patchCustomer updates language options and getCustomer retrieves them","description":"","line":19,"type":"scenario","tags":[{"name":"@rest_regression","line":1},{"name":"@PC","line":1},{"name":"@GC","line":1}],"before":[{"match":{"location":{"filepath":{"filename":"features/support/hooks.rb"},"lines":{"data":["20"]}}},"result":{"status":"passed","duration":2402000000}}],"steps":[{"keyword":"Given ","name":"the user establish an agreement for person with single role by calling establish_agreement_v2 service using below data","line":19,"match":{"location":"features/step_definitions/stepdef_eas.rb:3"},"result":{"status":"passed","duration":2053000000}},{"keyword":"When ","name":"the User calls patch_customer to add language_preference options as below","line":19,"match":{"location":"features/step_definitions/stepdef_PC.rb:1"},"result":{"status":"passed","duration":1659000000}},{"keyword":"Then ","name":"the User calls get_customer to verify the response for following data","line":19,"match":{"location":"features/step_definitions/stepdef_gc.rb:7"},"result":{"status":"passed","duration":3629000000}}]},{"id":"testing-the-patchcustomer-and-getcustomer-rest-services;validating-patchcustomer-updates-language-options-and-getcustomer-retrieves-them;;3","keyword":"Scenario Outline","name":"Validating patchCustomer updates language options and getCustomer retrieves them","description":"","line":20,"type":"scenario","tags":[{"name":"@rest_regression","line":1},{"name":"@PC","line":1},{"name":"@GC","line":1}],"before":[{"match":{"location":{"filepath":{"filename":"features/support/hooks.rb"},"lines":{"data":["20"]}}},"result":{"status":"passed","duration":1981000000}}],"steps":[{"keyword":"Given ","name":"the user establish an agreement for person with single role by calling establish_agreement_v2 service using below data","line":20,"match":{"location":"features/step_definitions/stepdef_eas.rb:3"},"result":{"status":"passed","duration":948000000}},{"keyword":"When ","name":"the User calls patch_customer to add language_preference options as below","line":20,"match":{"location":"features/step_definitions/stepdef_PC.rb:1"},"result":{"status":"passed","duration":1024000000}},{"keyword":"Then ","name":"the User calls get_customer to verify the response for following data","line":20,"match":{"location":"features/step_definitions/stepdef_gc.rb:7"},"result":{"status":"passed","duration":3376000000}}]},{"id":"testing-the-patchcustomer-and-getcustomer-rest-services;validating-patchcustomer-updates-language-options-and-getcustomer-retrieves-them;;4","keyword":"Scenario Outline","name":"Validating patchCustomer updates language options and getCustomer retrieves them","description":"","line":21,"type":"scenario","tags":[{"name":"@rest_regression","line":1},{"name":"@PC","line":1},{"name":"@GC","line":1}],"before":[{"match":{"location":{"filepath":{"filename":"features/support/hooks.rb"},"lines":{"data":["20"]}}},"result":{"status":"passed","duration":2011000000}}],"steps":[{"keyword":"Given ","name":"the user establish an agreement for person with single role by calling establish_agreement_v2 service using below data","line":21,"match":{"location":"features/step_definitions/stepdef_eas.rb:3"},"result":{"status":"passed","duration":1036000000}},{"keyword":"When ","name":"the User calls patch_customer to add language_preference options as below","line":21,"match":{"location":"features/step_definitions/stepdef_PC.rb:1"},"result":{"status":"passed","duration":978000000}},{"keyword":"Then ","name":"the User calls get_customer to verify the response for following data","line":21,"match":{"location":"features/step_definitions/stepdef_gc.rb:7"},"result":{"status":"passed","duration":3350000000}}]},{"id":"testing-the-patchcustomer-and-getcustomer-rest-services;validating-patchcustomer-updates-language-options-and-getcustomer-retrieves-them;;5","keyword":"Scenario Outline","name":"Validating patchCustomer updates language options and getCustomer retrieves them","description":"","line":22,"type":"scenario","tags":[{"name":"@rest_regression","line":1},{"name":"@PC","line":1},{"name":"@GC","line":1}],"before":[{"match":{"location":{"filepath":{"filename":"features/support/hooks.rb"},"lines":{"data":["20"]}}},"result":{"status":"passed","duration":2790000000}}],"steps":[{"keyword":"Given ","name":"the user establish an agreement for person with single role by calling establish_agreement_v2 service using below data","line":22,"match":{"location":"features/step_definitions/stepdef_eas.rb:3"},"result":{"status":"passed","duration":1074000000}},{"keyword":"When ","name":"the User calls patch_customer to add language_preference options as below","line":22,"match":{"location":"features/step_definitions/stepdef_PC.rb:1"},"result":{"status":"passed","duration":1073000000}},{"keyword":"Then ","name":"the User calls get_customer to verify the response for following data","line":22,"match":{"location":"features/step_definitions/stepdef_gc.rb:7"},"result":{"status":"passed","duration":3359000000}}]},{"id":"testing-the-patchcustomer-and-getcustomer-rest-services;validating-patchcustomer-updates-language-options-and-getcustomer-retrieves-them;;6","keyword":"Scenario Outline","name":"Validating patchCustomer updates language options and getCustomer retrieves them","description":"","line":23,"type":"scenario","tags":[{"name":"@rest_regression","line":1},{"name":"@PC","line":1},{"name":"@GC","line":1}],"before":[{"match":{"location":{"filepath":{"filename":"features/support/hooks.rb"},"lines":{"data":["20"]}}},"result":{"status":"passed","duration":2404000000}}],"steps":[{"keyword":"Given ","name":"the user establish an agreement for person with single role by calling establish_agreement_v2 service using below data","line":23,"match":{"location":"features/step_definitions/stepdef_eas.rb:3"},"result":{"status":"passed","duration":933000000}},{"keyword":"When ","name":"the User calls patch_customer to add language_preference options as below","line":23,"match":{"location":"features/step_definitions/stepdef_PC.rb:1"},"result":{"status":"passed","duration":981000000}},{"keyword":"Then ","name":"the User calls get_customer to verify the response for following data","line":23,"match":{"location":"features/step_definitions/stepdef_gc.rb:7"},"result":{"status":"passed","duration":3293000000}}]},{"id":"testing-the-patchcustomer-and-getcustomer-rest-services;validating-patchcustomer-updates-language-options-and-getcustomer-retrieves-them;;7","keyword":"Scenario Outline","name":"Validating patchCustomer updates language options and getCustomer retrieves them","description":"","line":24,"type":"scenario","tags":[{"name":"@rest_regression","line":1},{"name":"@PC","line":1},{"name":"@GC","line":1}],"before":[{"match":{"location":{"filepath":{"filename":"features/support/hooks.rb"},"lines":{"data":["20"]}}},"result":{"status":"passed","duration":1871000000}}],"steps":[{"keyword":"Given ","name":"the user establish an agreement for person with single role by calling establish_agreement_v2 service using below data","line":24,"match":{"location":"features/step_definitions/stepdef_eas.rb:3"},"result":{"status":"passed","duration":1065000000}},{"keyword":"When ","name":"the User calls patch_customer to add language_preference options as below","line":24,"match":{"location":"features/step_definitions/stepdef_PC.rb:1"},"result":{"status":"passed","duration":1005000000}},{"keyword":"Then ","name":"the User calls get_customer to verify the response for following data","line":24,"match":{"location":"features/step_definitions/stepdef_gc.rb:7"},"result":{"status":"passed","duration":3181000000}}]}]}]

**Comment by mpkorstanje** [comment]
This  appears to be the problematic section. Location contains more then just a string now. Is ruby doing something new?

```json
"before": [
  {
    "match": {
      "location": {
        "filepath": {
          "filename": "features/support/hooks.rb"
        },
        "lines": {
          "data": [
            "20"
          ]
        }
      }
    },
    "result": {
      "status": "passed",
      "duration": 2402000000
    }
  }
],
```

**Comment by mpkorstanje** [comment]
https://github.com/cucumber/cucumber-ruby/blob/0161920e5dde15161d74091ffb3ac04aef0b1938/lib/cucumber/formatter/json.rb#L200
```ruby
def create_match_hash(test_step, result)
    { location: test_step.action_location.to_s }
end

```
Doesn't look like this comes from the ruby json formatter. Are you using a custom json formatter? I'm going to need a minimal reproducer to solve this.

**Comment by kalyanhi** [comment]
In my cucumber.yml file, I have created profile(json_report:) with below code to generate json report,  with this same profile I was able to generate reports using cucumber reports jenkins plugin. 
json_report: --format progress --format json  --out=report.json

**Comment by mpkorstanje** [comment]
What is the output of `cucumber --version` on the build server?

**Comment by kalyanhi** [comment]
cucumber (2.0.2)
cucumber-core (1.2.0)

Please let me know in case if you need more information.
[image: Inline image 1]
[image: Inline image 2]

**Comment by mpkorstanje** [comment]
Well. That explains the problem. You need to update your version of cucumber-ruby to at least v2.3.2

https://github.com/cucumber/cucumber-ruby/commit/3153491a741ade59f902f0c5f57e3a520f015155

**Comment by kalyanhi** [comment]
Thank you so much.

I made changes to exsiting version and it is working and I will update to
 v2.3.2

def create_match_hash(test_step, result)
  { location: test_step.action_location.to_s}
end

Thanks,

Kalyan.

**Comment by damianszczepanik** [comment]
@mpkorstanje  thanks
