### ISSUE TITLE
NPE Not able to Generate cucumber report through jenkins

### ISSUE THREAD

**Issue by VinoSakthi** [jenkinsci/cucumber-reports-plugin#159]
I'm using jenkins pipeline project to execute cucumber tests

step([$class: 'CucumberReportPublisher', failedFeaturesNumber: 0, failedScenariosNumber: 0, failedStepsNumber: 0, fileExcludePattern: '', fileIncludePattern: '**/*.json', jsonReportDirectory: '', pendingStepsNumber: 0, skippedStepsNumber: 0, undefinedStepsNumber: 0])

Something went wrong with project  build 7

java.lang.NullPointerException
	at net.masterthought.cucumber.util.Util.toValidFileName(Util.java:82)
	at net.masterthought.cucumber.json.Feature.calculateReportFileName(Feature.java:192)
	at net.masterthought.cucumber.json.Feature.setMetaData(Feature.java:172)
	at net.masterthought.cucumber.ReportParser.setMetadata(ReportParser.java:97)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:60)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:87)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:174)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:112)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:78)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:65)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Trying to generate report from following files. Make sure they are valid cucumber report files:
           C:\Program Files (x86)\Jenkins\jobs\UI\builds\7\cucumber-html-reports\.cache\target\cucumber-usage.json
           C:\Program Files (x86)\Jenkins\jobs\UI\builds\7\cucumber-html-reports\.cache\target\cucumber.json

**Comment by VinoSakthi** [comment]
![capture](https://user-images.githubusercontent.com/29659426/27484805-3a4ff4c0-5848-11e7-8e7e-361e36cc5c59.PNG)

**Comment by damianszczepanik** [comment]
Show me JSON file

**Comment by VinoSakthi** [comment]
Hi Damian,

I have attached json.zip file which contains cucumber.json and cucumber-usage.json.  

[JSON.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/1105213/JSON.zip)

**Comment by damianszczepanik** [comment]
The problem is that one file has `uri` while second does not provide such information

**Comment by VinoSakthi** [comment]
Hi Damian,

Now Able to Generate Cucumber reports after excluded the other file 

Thanks for the solution.

**Comment by damianszczepanik** [comment]
Cool, can you add note how did you fix this problem?

**Comment by achaudry31** [comment]
I am having the same issue. 
ava.lang.NullPointerException
	at net.masterthought.cucumber.util.Util.toValidFileName(Util.java:75)
	at net.masterthought.cucumber.json.Feature.calculateReportFileName(Feature.java:182)
	at net.masterthought.cucumber.json.Feature.setMetaData(Feature.java:165)
	at net.masterthought.cucumber.ReportResult.<init>(ReportResult.java:66)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:89)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:404)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:324)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1073)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Trying to generate report from following files. Make sure they are valid cucumber report files:
           C:\Users\laptop\Jenkins\jobs\QFRDB\builds\35\cucumber-html-reports\.cache\cucumber-usage.json
           C:\Users\laptop\Jenkins\jobs\QFRDB\builds\35\cucumber-html-reports\.cache\cucumber.json

**Comment by achaudry31** [comment]
please help
I do not know how to get the JSON file here and attach it
