### ISSUE TITLE
ValidationException: not proper Cucumber report

### ISSUE THREAD

**Issue by Gaurang033** [jenkinsci/cucumber-reports-plugin#169]
I was using this plugin for more than a year now and everything was working fine until a few days back when I upgraded my Jenkins. 
Now when I click on the report it says following error message 

I haven't done any changes into the project so there couldn't be a way that jsons are not proper. 

> net.masterthought.cucumber.ValidationException: File '/var/lib/jenkins/jobs/hob_name/builds/2479/cucumber-html-reports/.cache/cucumber-json-report.json' is not proper Cucumber report!
> 	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:87)
> 	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:58)
> 	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:87)
> 	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:269)
> 	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:207)
> 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
> 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
> 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1072)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
> 	at hudson.model.Run.execute(Run.java:1760)
> 	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:542)
> 	at hudson.model.ResourceController.execute(ResourceController.java:97)
> 	at hudson.model.Executor.run(Executor.java:405)
> Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
>  at [Source: java.io.InputStreamReader@54b59dae; line: 1, column: 0]
> 	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
> 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3838)
> 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
> 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2887)
> 	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:81)
> 	... 14 more

**Comment by damianszczepanik** [comment]
Show me JSON file

**Comment by rahulkulkarniyahoo** [comment]
hi @damianszczepanik I received similar error:
****************************************************************** 
*********************** ERROR ********************************** 
****************************************************************** 

net.masterthought.cucumber.ValidationException: File '/XXXX/jenkins/jobs/NativeApp_iOS_Regression/builds/7/cucumber-html-reports/.cache/site/serenity/nivo-slider/3.2/nivoslider.jquery.json' is not proper Cucumber report!
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:87)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:58)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:87)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:269)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:207)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:730)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1072)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
	at hudson.model.Run.execute(Run.java:1760)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:542)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of net.masterthought.cucumber.json.Feature[] out of START_OBJECT token
 at [Source: java.io.InputStreamReader@864a7cb; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.handleNonArray(ObjectArrayDeserializer.java:275)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:179)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2887)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:81)
	... 14 more


****************************************************************** 
********************** NIVO SLIDER jquery.json ********************** 
****************************************************************** 
{
  "name": "nivoslider",
  "version": "3.2",
  "title": "Nivo Slider",
  "author": {
    "name": "Gilbert Pellegrom",
    "url": "http://gilbert.pellegrom.me"
  },
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/gilbitron/Nivo-Slider/blob/master/license.txt"
    }
  ],
  "dependencies": {
    "jquery": ">=1.7"
  },
  "description": "The Most Awesome jQuery Image Slider.",
  "keywords": [
    "slider",
    "animation",
    "effect"
  ],
  "homepage": "http://nivo.dev7studios.com",
  "docs": "http://nivo.dev7studios.com/support",
  "demo": "http://nivo.dev7studios.com/demos",
  "download": "http://nivo.dev7studios.com/pricing",
  "bugs": "https://github.com/gilbitron/Nivo-Slider/issues"
}
****************************************************************** 
********************** JSON FILE *******************************
****************************************************************** 
[
  {
    "line": 1,
    "elements": [
      {
        "before": [
          {
            "result": {
              "duration": 32102794905,
              "status": "passed"
            },
            "match": {
              "location": "StepDefinitions.startUp()"
            }
          }
        ],
        "line": 36,
        "name": "Verify Guest Profile login and Select Police Station appears on Map @lancaster",
        "description": "",
        "id": "login-and-switching-profiles-for-lancaster;verify-guest-profile-login-and-select-police-station-appears-on-map-@lancaster;;2",
        "after": [
          {
            "result": {
              "duration": 669218730,
              "status": "passed"
            },
            "match": {
              "location": "StepDefinitions.tearDown()"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario Outline",
        "steps": [
          {
            "result": {
              "duration": 105139080,
              "status": "passed"
            },
            "line": 27,
            "name": "I am on Lancaster App",
            "match": {
              "location": "StepDefinitions.i_am_on_Lancaster_App()"
            },
            "keyword": "Given "
          },
          {
            "result": {
              "duration": 9488782143,
              "status": "passed"
            },
            "line": 28,
            "name": "I select profile \"City, Coast \u0026 Countryside\"",
            "match": {
              "arguments": [
                {
                  "val": "City, Coast \u0026 Countryside",
                  "offset": 18
                }
              ],
              "location": "StepDefinitions.i_select_profile(String)"
            },
            "matchedColumns": [
              0
            ],
            "keyword": "When "
          },
          {
            "result": {
              "duration": 6552287484,
              "status": "passed"
            },
            "line": 29,
            "name": "I am able to login",
            "match": {
              "location": "StepDefinitions.i_am_able_to_login()"
            },
            "keyword": "Then "
          },
          {
            "result": {
              "duration": 10749743595,
              "status": "passed"
            },
            "line": 30,
            "name": "I can click on Map tile",
            "match": {
              "location": "StepDefinitions.i_can_click_on_Map_tile()"
            },
            "keyword": "And "
          },
          {
            "result": {
              "duration": 3813902194,
              "status": "passed"
            },
            "line": 31,
            "name": "I can search for \"Police Stations (2)\"",
            "match": {
              "arguments": [
                {
                  "val": "Police Stations (2)",
                  "offset": 18
                }
              ],
              "location": "StepDefinitions.i_can_search_for(String)"
            },
            "matchedColumns": [
              1
            ],
            "keyword": "And "
          },
          {
            "result": {
              "duration": 4108974459,
              "status": "passed"
            },
            "line": 32,
            "name": "select the \"Lancaster Police Station\"",
            "match": {
              "arguments": [
                {
                  "val": "Lancaster Police Station",
                  "offset": 12
                }
              ],
              "location": "StepDefinitions.select_the(String)"
            },
            "matchedColumns": [
              2
            ],
            "keyword": "And "
          },
          {
            "result": {
              "duration": 17091734828,
              "status": "passed"
            },
            "line": 33,
            "name": "I can confirm the Map Pin exists with \"Lancaster Police Station\"",
            "match": {
              "arguments": [
                {
                  "val": "Lancaster Police Station",
                  "offset": 39
                }
              ],
              "location": "StepDefinitions.i_can_confirm_the_Map_Pin_exists_with(String)"
            },
            "matchedColumns": [
              2
            ],
            "keyword": "And "
          }
        ],
        "tags": [
          {
            "line": 25,
            "name": "@guest"
          },
          {
            "line": 25,
            "name": "@smoke"
          },
          {
            "line": 25,
            "name": "@lancaster"
          },
          {
            "line": 25,
            "name": "@regression"
          },
          {
            "line": 25,
            "name": "@test"
          }
        ]
      }
    ],
    "name": "Login and Switching Profiles for Lancaster",
    "description": "",
    "id": "login-and-switching-profiles-for-lancaster",
    "keyword": "Feature",
    "uri": "Lancaster.feature"
  }
]

**Comment by Gaurang033** [comment]
with earlier version I just provided the location of **target** folder and patter as ***.json** to pick the correct file and it was working. After upgrading I faced this issue. 

however, after providing the path to only **cucumber-json-report.json** (it's default name) file, it started working again.

**Comment by gunabca** [comment]
This worked for me ! Awesome Gaurang033

**Comment by mkelliher3** [comment]
Hi, 

I am having similar issue. How can you resolve it? 

My code for TestRunner is: 

`@CucumberOptions(
        glue = {"classpath:com.....", "classpath:com.......cucumber"},
        features = {"src/test/resources/com/....../qa/cucumber/"},
        plugin = {"pretty", "html:target/cucumber", "json:target/cucumber-reports/cucumber.json"})
public class ExchangeTestRunner extends CucumberMultiCountryRunner {

}`

It works well for Cucumber scenarios. However, the HTML report didn't work for any feature files that use 'Background' keyword. 

https://github.com/jenkinsci/cucumber-reports-plugin/issues/229

**Comment by radhikasivakumar** [comment]
After updating version its working fine for me
 <groupId>net.masterthought</groupId>
				<artifactId>maven-cucumber-reporting</artifactId>
				<version>3.15.0</version>

**Comment by YashPethe** [comment]
Hi, my html report was successfully generating. But once i clean and install maven intentionally i am getting error while generating html report that 'None report file was added'

I also noticed after maven clean amd install some of the folder from target and resource folder was erased. 

My testRunner file could not be able to read feature file due to that error is coming. Did anyone face this issue?

**Comment by ptrthomas** [comment]
@YashPethe no

**Comment by Hima-QA** [comment]
```
net.masterthought.cucumber.ValidationException: None report file was added!
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:61)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:93)
	at net.masterthought.cucumber.CucumberReportGeneratorMojo.execute(CucumberReportGeneratorMojo.java:222)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**I am getting the above error. My cucumber.json file is correct as it runs perfectly fine in _**Jenkins**_  and generates overview-feature.html but in eclipse when i open the overview-feature.html  it shows this error**

**Comment by Hima-QA** [comment]
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.qa</groupId>
	<artifactId>CucumberPgObj</artifactId>
	<version>0.0.1-SNAPSHOT</version>



	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.18.1</version>
				<configuration>
					<testFailureIgnore>true</testFailureIgnore>
					<suiteXmlFiles>
						<suiteXmlFile>src/test/resources/runner/testng.xml</suiteXmlFile>
					</suiteXmlFiles>
				</configuration>
			</plugin>


			<!-- Latest Cucumber JVM Reports Plugin -->
			<!-- https://mvnrepository.com/artifact/net.masterthought/maven-cucumber-reporting -->

			<plugin>
				<groupId>net.masterthought</groupId>
				<artifactId>maven-cucumber-reporting</artifactId>
				<version>5.3.0</version>

				<executions>
					<execution>
						<id>execution</id>
						<phase>verify</phase>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<projectName>CucumberPgObj</projectName> <!-- Replace with project name -->
							<outputDirectory>${project.build.directory}/cucumber-reports/advanced-reports</outputDirectory>
							<cucumberOutput>${project.build.directory}/cucumber-reports/cucumber.json</cucumberOutput>
							<buildNumber>1</buildNumber>
							<parallelTesting>false</parallelTesting>
							<skip>false</skip>
							<inputDirectory>${project.build.directory}/cucumber-reports</inputDirectory>
							<jsonFiles> <!-- supports wildcard or name pattern -->
								<param>${project.build.directory}/cucumber-reports/cucumber.json</param>
							</jsonFiles> <!-- optional, defaults to outputDirectory if not specified -->
							<classificationDirectory>${project.build.directory}/cucumber-reports</classificationDirectory>
							<checkBuildResult>false</checkBuildResult>
						</configuration>
					</execution>
				</executions>



			</plugin>

		</plugins>
	</build>


	<dependencies>

		<!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java -->
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.141.59</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/io.github.bonigarcia/webdrivermanager -->
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>4.0.0</version>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>4.8.1</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/io.cucumber/cucumber-core -->
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>4.8.1</version>
		</dependency>


		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-picocontainer</artifactId>
			<version>4.8.1</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>4.8.1</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-testng</artifactId>
			<version>4.8.1</version>
			<scope>test</scope>
		</dependency>




		<!-- Extent Reports 4 Plugin -->
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports-cucumber4-adapter</artifactId>
			<version>1.0.12</version>
			<exclusions>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>cucumber-java</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>cucumber-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>


		<!-- https://mvnrepository.com/artifact/net.masterthought/cucumber-reporting -->
		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>5.3.0</version>
		</dependency>

	</dependencies>

</project>
```
**Do i need to make any change tomy pom.xml file?**

**Comment by damianszczepanik** [comment]
You need to pass proper JSON file

**Comment by kalpana2626** [comment]
I am getting below error when I run through command line. It was working fine before and nothing changed and started getting below error. Any help appreciated. 

net.masterthought.cucumber.ValidationException: File 'C:\Users\VHAWASVATHAK\eclipse-workspace\VAOSReports\target\jsonReports\cucumber-reports.json' is not proper Cucumber report!
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:104)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:72)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:93)
	at net.masterthought.cucumber.CucumberReportGeneratorMojo.execute(CucumberReportGeneratorMojo.java:222)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (InputStreamReader); line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4344)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4189)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3218)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:93)
	... 25 more




pom.xml


<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  
  <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>5.4.0</version>
                <executions>
                    <execution>
                        <id>execution</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <projectName>cucumber-jvm-example</projectName>
                            
                            <skip>false</skip>
                            
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            
                            <inputDirectory>C:/Users/VHAWASVATHAK/eclipse-workspace/WeekendtryVAOSAPIFramework/target/jsonReports</inputDirectory>
                            <jsonFiles>
                                
                                <param>C:/Users/VHAWASVATHAK/eclipse-workspace/WeekendtryVAOSAPIFramework/target/jsonReports/cucumber-reports.json</param>
                            </jsonFiles>
                            
                      
                            <parallelTesting>false</parallelTesting>
                            
                            <mergeFeaturesById>false</mergeFeaturesById>
                            
                            <mergeFeaturesWithRetest>false</mergeFeaturesWithRetest>
                            
                            <checkBuildResult>false</checkBuildResult>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

  <dependencies>
  
    
    
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>4.8.0</version>
</dependency>


<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-junit</artifactId>
    <version>4.8.0</version>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured</artifactId>
    <version>4.1.2</version>
    <scope>test</scope>
</dependency>


<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.10.1</version>
</dependency>

<dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.12</version>
    <scope>test</scope>
</dependency>
  </dependencies>
</project>

**Comment by gunabca** [comment]
Could you check whether the json file created is in proper format or uses UTF-8 encoding?

**Comment by kalpana2626** [comment]
> Could you check whether the json file created is in proper format or uses UTF-8 encoding?

Thank you for quick reply. json format is correct and when I run through command line empty json file is creating.

TestRunner.java

package cucumber.Options;

import org.junit.runner.RunWith;

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;



	@RunWith(Cucumber.class)
	@CucumberOptions(features="src/test/java/features",plugin = "json:target/jsonReports/cucumber-reports.json",glue= {"stepDefinations"})
	
	public class TestRunner {	
	
}

**Comment by ahewstone** [comment]
Could anyone fix this issue?

**Comment by pramodnimmagadda-kore** [comment]
net.masterthought.cucumber.ValidationException: No report file was added!
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:61)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:97)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:563)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:434)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:814)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:763)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1072)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:707)
	at hudson.model.Run.execute(Run.java:1921)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)



i am getting above error while running the cucumber report from jenkins local.any advise please ?
