### ISSUE TITLE
Error on embedding screenshot with cucumberjs 3 json

### ISSUE THREAD

**Issue by innocentiv** [jenkinsci/cucumber-reports-plugin#193]
When I try to convert a report with screenshot generated by cucumber-js 3 I encounter this error:

```
net.masterthought.cucumber.ValidationException: File '/var/lib/jenkins/jobs/ofs/jobs/ytos-armaniexchange/branches/pilot-nightwatch-update.bvh6k0/builds/8/cucumber-html-reports/.cache/report.json' is not proper Cucumber report!
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:87)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:58)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:87)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:284)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:219)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: java.lang.Object[][1]->net.masterthought.cucumber.json.Feature["elements"]->java.lang.Object[][0]->net.masterthought.cucumber.json.Element["steps"]->java.lang.Object[][40]->net.masterthought.cucumber.json.Step["embeddings"]->java.lang.Object[][0])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:360)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:207)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2887)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:81)
	... 14 more
Caused by: java.lang.NullPointerException
	at net.masterthought.cucumber.json.deserializers.EmbeddingDeserializer.deserialize(EmbeddingDeserializer.java:27)
	at net.masterthought.cucumber.json.deserializers.EmbeddingDeserializer.deserialize(EmbeddingDeserializer.java:22)
	at net.masterthought.cucumber.json.deserializers.CucumberJsonDeserializer.deserialize(CucumberJsonDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
	... 36 more
```

The error presented itself after upgrading to cucumber-js 3 and is present only when I encounter a failure and a screenshot is embedded in the step result.
Analizing the relevent part of the JSON file I noticed discrepancy in the JSON output with the previous cucumber-js implementation:

The output in cucumber-js 2
```
            "embeddings": [
              {
                "data": "iVBORw0KGgoA...",
                "mime_type": "image/png"
              }
            ],
```

The output in cucumber-js 3
```
            "embeddings": [
              {
                "data": "iVBORw0KGgoA...",
                "media": {
                  "type": "image/png"
                }
              }
            ]
```

I'm not a Java developer but I think the mapping Exception is expected if the EmbeddingDeserializer found in https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/json/deserializers/EmbeddingDeserializer.java is used.

```
    public Embedding deserialize(JsonNode rootNode, Configuration configuration) {
        String data = rootNode.get("data").asText();
        String mimeType = rootNode.get("mime_type").asText();

        Embedding embedding = new Embedding(mimeType, data);
```

The specs for the cucumberjs JSON formatter here: https://github.com/cucumber/cucumber-js/blob/master/src/formatter/json_formatter_spec.js

```
      it('outputs the step with embeddings', function() {
        const features = JSON.parse(this.output)
        expect(features[0].elements[0].steps[0].embeddings).to.eql([
          { data: 'first data', media: { type: 'first media type' } },
          { data: 'second data', media: { type: 'second media type' } }
        ])
      })
```

There is a way to resolve this issue? I reported it here because I'm not quite sure which project is responsible to fix this.

**Comment by damianszczepanik** [comment]
Looks like good candidate to fix and keep support for cucumber-js alive. Can you share link to the specification what is the formal JSON for embeddings as this is different than cucumber-jvm?

**Comment by innocentiv** [comment]
The only specification I found was the one I already linked in the issue (https://github.com/cucumber/cucumber-js/blob/master/src/formatter/json_formatter_spec.js)

I think the change was driven by the adoption of the event protocol of cucumber inside the formatter code: https://docs.cucumber.io/event-protocol/

Relevant issue: https://github.com/cucumber/cucumber/issues/187

**Comment by skruijt** [comment]
I would love to see this issue fixed. As a workaround, I'm currently creating the report manually and publishing it as HTML. But it would be so much better if I could use this plugin also whenever there are screenshots.

**Comment by damianszczepanik** [comment]
I'm not going to fix it as the relevant issue is resolved

**Comment by stefankruijt** [comment]
In the relevant issue, I read that the JSON format is being phased out. Is there any alternative I'm not aware of? or is there any way to get this plugin to work with cucumber-js 3 without going back to cucumber-js 2?

**Comment by achingbrain** [comment]
I've come across this problem too after upgrading Cucumber JS from v2 to v3.  We're now having to pre-process the json report files to add the `mime_type` property back to members of the `embeddings` array in order to stop `cucumber-reports-plugin` from exploding.

> I'm not going to fix it as the relevant issue is resolved

@damianszczepanik I hope you'll reconsider and patch up this plugin so it'll work with Cucumber V3.

**Comment by damianszczepanik** [comment]
Recommend to downgrade the cucumberjs library or change to something else as you see this is not mature solution

**Comment by innocentiv** [comment]
Sadly, I use cucumberjs as peer dependency of nightwatch-cucumber. To downgrade cucumberjs I would have to downgrade nightwatch cucumber. And this would introduce other bugs.

**Comment by achingbrain** [comment]
We had to upgrade Cucumber JS from v2 to v3 to fix other problems so downgrading isn't an option for us either.

**Comment by achingbrain** [comment]
I've submitted a PR that should resolve this issue as damianszczepanik/cucumber-reporting#694 - it'd be great if that could be merged and a new version of this plugin released.

**Comment by damianszczepanik** [comment]
Then what I can recommend is to push cucumber-js team to fix the problem and not ask to fix all other dependent libraries team to apply workaround
