### ISSUE TITLE
java.lang.SecurityException: Rejected: gherkin.formatter.model.Feature

### ISSUE THREAD

**Issue by erikhakansson** [jenkinsci/cucumber-reports-plugin#210]
Hello!

I'm getting the following exception:

~~~
09:18:54 09:18:54 java.lang.SecurityException: Rejected: gherkin.formatter.model.Feature
09:18:54 09:18:54 	at hudson.remoting.ClassFilter.check(ClassFilter.java:75)
09:18:54 09:18:54 	at hudson.remoting.MultiClassLoaderSerializer$Input.resolveClass(MultiClassLoaderSerializer.java:129)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1826)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2000)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
09:18:54 09:18:54 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
09:18:54 09:18:54 	at java.util.ArrayList.readObject(ArrayList.java:791)
09:18:54 09:18:54 	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
09:18:54 09:18:54 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:18:54 09:18:54 	at java.lang.reflect.Method.invoke(Method.java:498)
09:18:54 09:18:54 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2136)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
09:18:54 09:18:54 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
09:18:54 09:18:54 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
09:18:54 09:18:54 	at hudson.remoting.UserRequest.deserialize(UserRequest.java:277)
09:18:54 09:18:54 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
09:18:54 09:18:54 	at hudson.remoting.Channel.call(Channel.java:909)
09:18:54 09:18:54 	at hudson.FilePath.act(FilePath.java:998)
09:18:54 09:18:54 	at hudson.FilePath.act(FilePath.java:987)
09:18:54 09:18:54 	at org.jenkinsci.plugins.cucumber.jsontestsupport.DefaultTestResultParserImpl.parseResult(DefaultTestResultParserImpl.java:101)
09:18:54 09:18:54 	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberJSONParser.parseResult(CucumberJSONParser.java:101)
09:18:54 09:18:54 	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberTestResultArchiver.publishReport(CucumberTestResultArchiver.java:128)
09:18:54 09:18:54 	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberTestResultArchiver.perform(CucumberTestResultArchiver.java:113)
09:18:54 09:18:54 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
09:18:54 09:18:54 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
09:18:54 09:18:54 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
09:18:54 09:18:54 	at hudson.security.ACL.impersonate(ACL.java:274)
09:18:54 09:18:54 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
09:18:54 09:18:54 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
09:18:54 09:18:54 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09:18:54 09:18:54 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
09:18:54 09:18:54 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
09:18:54 09:18:54 	at java.lang.Thread.run(Thread.java:748)
~~~

I'm pretty sure it's Jenkins' fault. Jenkins 2.102 says this: 

> JEP-200: "Switch Remoting/XStream blacklist to a whitelist" has been integrated to this release. This change implies a HIGH RISK of regressions in plugins. See [this](https://jenkins.io/blog/2018/01/13/jep-200/) blogpost for list of plugins known to be affected, with instructions how to resolve possible problems. 

So it seems some changes are necessary to make the plugin work with Jenkins 2.102+

**Comment by erikhakansson** [comment]
Terribly sorry, I messed up. This issue was not at all connected to this Plugin!
