### ISSUE TITLE
NoSuchFileException when trying to archive test results with 3.14.0

### ISSUE THREAD

**Issue by mwoodland** [jenkinsci/cucumber-reports-plugin#221]
After updating to version 3.14.0 of the plugin when we run the following step in our Jenkins file we get a NoSuchFileException:

`step([$class: 'CucumberTestResultArchiver', testResults: '**/*.json'])`

Downgrading back to 3.13.0 resolved the issue.

The exception is as follows:
`Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to RDHBLD21
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1737)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:313)
		at hudson.remoting.Channel.call(Channel.java:952)
		at hudson.FilePath.act(FilePath.java:998)
		at hudson.FilePath.act(FilePath.java:987)
		at hudson.FilePath.copyTo(FilePath.java:2079)
		at hudson.FilePath.copyTo(FilePath.java:2040)
		at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberTestResultArchiver.publishReport(CucumberTestResultArchiver.java:158)
		at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberTestResultArchiver.perform(CucumberTestResultArchiver.java:119)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
java.nio.file.NoSuchFileException: /data/jenkins/workspace/r_adm-cucumber-test_develop-ZTOA4JQT436S6NC27P3Q6BLVJJSSR4RCFSJB4GNG25X7KIGDL7GA/~/tmp/cuke_3284213593362351215.embed
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at hudson.FilePath$41.invoke(FilePath.java:2082)
	at hudson.FilePath$41.invoke(FilePath.java:2079)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2816)
	at hudson.remoting.UserRequest.perform(UserRequest.java:210)
	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
	at hudson.remoting.Request$2.run(Request.java:364)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: java.io.IOException: remote file operation failed: /data/jenkins/workspace/r_adm-cucumber-test_develop-ZTOA4JQT436S6NC27P3Q6BLVJJSSR4RCFSJB4GNG25X7KIGDL7GA/~/tmp/cuke_3284213593362351215.embed at hudson.remoting.Channel@2cf195e6:RDHBLD21
	at hudson.FilePath.act(FilePath.java:1005)
	at hudson.FilePath.act(FilePath.java:987)
	at hudson.FilePath.copyTo(FilePath.java:2079)
	at hudson.FilePath.copyTo(FilePath.java:2040)
Caused: java.io.IOException: Failed to copy /data/jenkins/workspace/r_adm-cucumber-test_develop-ZTOA4JQT436S6NC27P3Q6BLVJJSSR4RCFSJB4GNG25X7KIGDL7GA/~/tmp/cuke_3284213593362351215.embed to /var/lib/jenkins/jobs/Pathfinder/jobs/adm-cucumber-test/branches/develop/builds/3670/cucumber/embed/eyu-outstanding-report_-generation-and-report-sections/eyu-outstanding-report_-generation,-header-&-sections/cuke_3284213593362351215.embed
	at hudson.FilePath.copyTo(FilePath.java:2043)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberTestResultArchiver.publishReport(CucumberTestResultArchiver.java:158)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberTestResultArchiver.perform(CucumberTestResultArchiver.java:119)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by mwoodland** [comment]
I think I've raised this against the wrong plugin.
