### ISSUE TITLE
Jenkins: failures due to an extra “%402” character in the location address

### ISSUE THREAD

**Issue by CarotUnima** [jenkinsci/cucumber-reports-plugin#231]
My runs are failing, I think due to existence of this suspicious character "%402" in the location addresses. When I check the folder name via terminal this folder name does not exist, while it appears in the Jenkins logs. I wonder anyone has similar experiences.

Here is a snippet from the error log:
Results :
`java.lang.RuntimeException: javascript evaluation failed: read('common.feature')
	at com.intuit.karate.Script.evalInNashorn(Script.java:423)
	at com.intuit.karate.Script.evalInNashorn(Script.java:394)
	at com.intuit.karate.Script.eval(Script.java:316)
	at com.intuit.karate.Script.eval(Script.java:194)
	at com.intuit.karate.Script.call(Script.java:1470)
	at com.intuit.karate.Script.callWithCache(Script.java:206)
	at com.intuit.karate.Script.callAndUpdateConfigAndAlsoVarsIfMapReturned(Script.java:1604)
	at com.intuit.karate.StepDefs.callOnceAndUpdateConfigAndVars(StepDefs.java:599)
	at ✽.* callonce read('common.feature')(wimo_android/wimo-case-upload-image.feature:4)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /var/jenkins_home/workspace/STG-maven-tests%402/target/test-classes/wimo_android/common.feature (No such file or directory)
	at com.intuit.karate.FileUtils.getFileStream(FileUtils.java:123)
	at com.intuit.karate.FileUtils.readFileAsString(FileUtils.java:101)
	at com.intuit.karate.FileUtils.readFile(FileUtils.java:87)
	at jdk.nashorn.internal.scripts.Script$Recompilation$464$15A$\^eval\_.L:1(<eval>:3)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117)
	at jdk.nashorn.internal.runtime.linker.JSObjectLinker.jsObjectScopeCall(JSObjectLinker.java:238)
	at jdk.nashorn.internal.scripts.Script$468$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)`

**Comment by damianszczepanik** [comment]
Show me JSON file
