### ISSUE TITLE
Possibly lacking support for tagless scenarios

### ISSUE THREAD

**Issue by sampsonliao** [jenkinsci/cucumber-reports-plugin#241]
According to the Cucumber API docs, a subset of scenarios can be run from the command line using a combination of the feature file and line number the Scenario can be found on. (See https://docs.cucumber.io/cucumber/api/#from-the-command-line Search for "Filtering by line")

This method of execution, i.e `mvn test -Dcucumber.options='<feature:line>'` rather than the typical `mvn test -Dcucumber.options='--tags "@smoke"'` works just fine.

However when combined with Cucumber Reporting, it fails to generate the contents of the json file that is normally created.
i.e when `mvn test -Dcucumber.options='<feature:line> --plugin json:target/cucumber.json'` is run,
the contents of cucumber.json will be: 
`[ ]`
and the resulting error is:

`net.masterthought.cucumber.ValidationException: Passed files have no features!
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:69)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:300)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:229)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

`Trying to generate report from following files. Make sure they are valid cucumber report files:
           /var/lib/jenkins/jobs/some_job/branches/master/builds/43/cucumber-html-reports/.cache/some_job/target/src/test/resources/com/cucumber.json`

Does Cucumber Reports currently have support for tests that run so-called "tagless" Scenarios?

**Comment by sampsonliao** [comment]
Example of I mean by "tagless" scenario just to be clear...:

`
Feature: Scenario with no tag

  Background:
     Tagless

  Scenario: Some description
    Given
    Then
`
