### ISSUE TITLE
Reporting Fails since 4.0 update

### ISSUE THREAD

**Issue by froemra** [jenkinsci/cucumber-reports-plugin#259]
All my Jenkins builds fail with the following NPE since Version 4.0. Works fine when switiching back to 3.2.0:

```
java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Enum.java:236)
	at net.masterthought.cucumber.reducers.ReducingMethod.valueOf(ReducingMethod.java:8)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:286)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:228)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

```	at java.lang.Thread.run(Thread.java:748)

**Comment by michelzanini** [comment]
I am having the same issue! Also my Jenkins was updated to 2.146 at the same time, so I am not sure this is related.

**Comment by michelzanini** [comment]
@damianszczepanik Can you please release a hotfix for this?

**Comment by froemra** [comment]
I am running Jenkins ver. 2.138.2 LTS. I don't think this is related to the Jenkins Version...

**Comment by michelzanini** [comment]
Yes true, I have reverted to 3.20 and is working now

**Comment by damianszczepanik** [comment]
My bad. I was aware of this problem, I was tested but looks like not enough!

Hot fix has been released now, wait for repo synchro. Also I'm really impressed you have upgraded the plugin within 24 h after release!
