### ISSUE TITLE
Cucumber Jenkins Report Fails with VelocityException

### ISSUE THREAD

**Issue by raghurok** [jenkinsci/cucumber-reports-plugin#273]
Cucumber report fails in jenkins with below exception consistently. Any help to resolve this is appreciated.

Plugin version: `4.1.0` and `4.2.0`

Invocation via Jenkinsfile as
```
post {
                always {
                    //generate cucumber reports
                    echo 'cucumber report'
                    cucumber fileIncludePattern: '**/*.json'
                    junit testResults: '**/target/surefire-reports/TEST-*.xml, **/target/failsafe-reports/TEST-*.xml'
                }
}
```

```
org.apache.velocity.exception.VelocityException: The specified logger class org.apache.velocity.runtime.log.Log4JLogChute does not implement the org.apache.velocity.runtime.log.LogChute interface.
	at org.apache.velocity.runtime.log.LogManager.createLogChute(LogManager.java:181)
Caused: org.apache.velocity.exception.VelocityException: Failed to initialize an instance of org.apache.velocity.runtime.log.Log4JLogChute with the current runtime configuration.
	at org.apache.velocity.runtime.log.LogManager.createLogChute(LogManager.java:220)
	at org.apache.velocity.runtime.log.LogManager.updateLog(LogManager.java:269)
	at org.apache.velocity.runtime.RuntimeInstance.initializeLog(RuntimeInstance.java:871)
Caused: org.apache.velocity.exception.VelocityException: Error initializing log: Failed to initialize an instance of org.apache.velocity.runtime.log.Log4JLogChute with the current runtime configuration.
	at org.apache.velocity.runtime.RuntimeInstance.initializeLog(RuntimeInstance.java:875)
	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:262)
	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:646)
	at org.apache.velocity.app.VelocityEngine.init(VelocityEngine.java:116)
	at net.masterthought.cucumber.generators.AbstractPage.<init>(AbstractPage.java:53)
	at net.masterthought.cucumber.generators.ErrorPage.<init>(ErrorPage.java:18)
	at net.masterthought.cucumber.ReportBuilder.generateErrorPage(ReportBuilder.java:223)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:104)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:310)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:237)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by damianszczepanik** [comment]
How about older versions?

**Comment by dionysiose** [comment]
@damianszczepanik, I have observed the same on 3.19.1.

**Comment by damianszczepanik** [comment]
Please share more details as I was not able to reproduce the problem :(
