### ISSUE TITLE
Reports failing since v4.2.0 (including 4.2.1)

### ISSUE THREAD

**Issue by grajsor** [jenkinsci/cucumber-reports-plugin#280]
Worked in 4.1.0, now we get:

Error
Something went wrong with project feature/cucumber_fix, build 2

org.apache.velocity.exception.MethodInvocationException: Invocation of method 'format' in  class net.masterthought.cucumber.util.StepNameFormatter threw exception java.lang.ArrayIndexOutOfBoundsException: 28 at /templates/macros/json/stepName.vm[line 3, column 47]
	at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:243)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:187)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:567)
	at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:71)
	at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:142)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:216)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:311)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:230)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:420)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:216)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:311)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:230)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:216)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:311)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:230)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:420)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.Template.merge(Template.java:356)
	at org.apache.velocity.Template.merge(Template.java:260)
	at net.masterthought.cucumber.generators.AbstractPage.generateReport(AbstractPage.java:78)
	at net.masterthought.cucumber.generators.AbstractPage.generatePage(AbstractPage.java:59)
	at net.masterthought.cucumber.ReportBuilder.generatePages(ReportBuilder.java:154)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:98)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:310)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:237)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 28
	at net.masterthought.cucumber.util.StepNameFormatter.surroundArguments(StepNameFormatter.java:40)
	at net.masterthought.cucumber.util.StepNameFormatter.format(StepNameFormatter.java:19)
	at sun.reflect.GeneratedMethodAccessor1125.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
	... 44 more

What gives?

TIA!

**Comment by damianszczepanik** [comment]
@grajsor attach JSON file so we can analyze and @ekalin can fix it

**Comment by grajsor** [comment]
Here it is, .json renamed to .txt 
[bpm.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/2610034/bpm.txt)

**Comment by damianszczepanik** [comment]
@grajsor the problem happens when ```val``` is empty

**Comment by ekalin** [comment]
It is indeed the same problem as damianszczepanik/cucumber-reporting#789; I'm working on it.

But to be sure, @grajsor, could you provide the step definition that leads to this result:
```
            "line": 29,
            "name": "ska decimalfältet innehålla ",
            "match": {
              "arguments": [
                {
                  "val": "",
                  "offset": 28
                }
              ],
              "location": "BpmSteps.skaDecimalfaltetInnehalla(String)"
            },
            "keyword": "Så "
          }
```

(There are several similar steps, I believe this one matches nothing at the end.)

**Comment by damianszczepanik** [comment]
Published

**Comment by tutaidalal** [comment]
Is it alreday fixed ? Can someone please share the verion number where it has been fixed.. I am using 4.7.0 and still getting the issue in very simple step.

**Comment by damianszczepanik** [comment]
This is fixed. Open new issue share logs and Json file
