### ISSUE TITLE
net.masterthought.cucumber.ValidationException: Passed files have no features!

### ISSUE THREAD

**Issue by rraymundo** [jenkinsci/cucumber-reports-plugin#291]
Cucumber report does not get generated when the JSON file only contains an empty array which result in FAILURE in the pipeline job. This happens when my test doesn't fail and no reruns are needed.

```
net.masterthought.cucumber.ValidationException: Passed files have no features!
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:78)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:323)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:247)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Trying to generate report from following files. Make sure they are valid cucumber report files:
           /var/lib/jenkins/jobs/qa-automation-part4/builds/60/cucumber-html-reports/.cache/log/cucumber.json
```

**Comment by damianszczepanik** [comment]
Did you follow with advice attached to this log?

**Comment by diana-papajohns** [comment]
Hi,
I'm facing the same issue.. cucumber.json is empty for the pass scenarios in Jenkins.. For failed-re-run scenarios it is working fine

**Comment by damianszczepanik** [comment]
why the report is empty? this does not look like valid output

**Comment by kzhou57** [comment]
HI 

Facing the same issue, it's some valid edge cases, it happens when no test scenario match the tag we passed in. It should not fail the test even through no test running.

**Comment by damianszczepanik** [comment]
Attach JSON file

**Comment by d-huynh** [comment]
Hi, I ran into the same probelm.
JSON file is just an empty array `[]`.

**Comment by SuayipTekin** [comment]
I have been having the same issue! Could not resolve it yet!

**Comment by leginj** [comment]
The cucumber tags you used are causing the runner to not find any matching tests. You can find this by doing a dry run on the Runner files individually which the tags and can remove the unused runner or modify the tag so that the runner finds some tests to execute

**Comment by kumarvinod22** [comment]
I'm also getting same, please provide solution what can do
net.masterthought.cucumber.ValidationException: Passed files have no features!
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:78)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:323)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:247)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Trying to generate report from following files. Make sure they are valid cucumber report files:
           /var/lib/jenkins/jobs/qa-automation-part4/builds/60/cucumber-html-reports/.cache/log/cucumber.json
