### ISSUE TITLE
Cucumber report failed to generate in Jenkins 

### ISSUE THREAD

**Issue by ankitsuhane** [jenkinsci/cucumber-reports-plugin#312]
First of all Many Thanks for creating such a nice plugin.
I have been using this plauin and very much appreciated by team.

**Issue**: Now we have created a framework and start developing automated test cases however for few of the times when we do not have to run all the features so at times json file generated with 0 bytes.
This is causing job failure in Jenkins with below error
My WebLeaveProcess.json file is generating with 0 bytes so i suspect this is reason for failure. 

**Error Message**
net.masterthought.cucumber.ValidationException: File 'C:\Users\MSP6962\.jenkins\jobs\CuExptag\builds\41\cucumber-html-reports\.cache\WebLeaveProcess.json' is not proper Cucumber report!
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:99)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:71)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:323)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:247)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (InputStreamReader); line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4145)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3049)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:93)
	... 14 more
Trying to generate report from following files. Make sure they are valid cucumber report files:
           C:\Users\MSP6962\.jenkins\jobs\CuExptag\builds\41\cucumber-html-reports\.cache\WebLeaveProcess.json
           C:\Users\MSP6962\.jenkins\jobs\CuExptag\builds\41\cucumber-html-reports\.cache\WebNewJoinerProcess.json

**Comment by ankitsuhane** [comment]
[WebLeaveProcess.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/3064680/WebLeaveProcess.zip)

**Comment by damianszczepanik** [comment]
Well, attached file is empty and this is why report cannot be generated

**Comment by ankitsuhane** [comment]
Thanks for your response.

Yes, I know json file is 0 bytes and that is what I mentioned in my problem statement. We have many features and we are executing only few of them due to which few output JSON files are coming 0 bytes. Is there any mechanism to ignore those 0 bytes files during runtime.
Please suggest .

**Comment by damianszczepanik** [comment]
You can configure the plugin so that case won't fail the report

**Comment by ankitsuhane** [comment]
Many thanks for your suggestion.
Can you please share any documentation or steps that has that kind of configuration mentioned?

**Comment by damianszczepanik** [comment]
Check readme
