### ISSUE TITLE
Getting builds/929/cucumber-html-reports/.cache does not exist on my Automation jobs

### ISSUE THREAD

**Issue by Blackbaud-JagjeetChadha** [jenkinsci/cucumber-reports-plugin#317]
Hi All,

Till yesterday my automation jobs was running without any issue on Jenkins and was creating cucumber reports but from today I started seeing below error related to Cucumber reports.

[CucumberReport] Preparing Cucumber Reports
[CucumberReport] Copied 0 json files from workspace "/builds/automationresults" to reports directory "/var/lib/jenkins/jobs/Automation Master - CPT/builds/929/cucumber-html-reports/.cache"
ERROR: Build step failed with exception
java.lang.IllegalStateException: basedir /var/lib/jenkins/jobs/Automation Master - CPT/builds/929/cucumber-html-reports/.cache does not exist.
	at org.apache.tools.ant.DirectoryScanner.scan(DirectoryScanner.java:879)
	at net.masterthought.jenkins.CucumberReportPublisher.findJsonFiles(CucumberReportPublisher.java:148)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:101)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:73)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at com.cloudbees.plugins.flow.FlowRun$BuildWithWorkspaceRunnerImpl.post2(FlowRun.java:196)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at com.cloudbees.plugins.flow.FlowRun.run(FlowRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Build step 'Cucumber reports' marked build as failure
Finished: FAILURE

Can anyone please suggest the possible solution for the same? Its urgent.

**Comment by damianszczepanik** [comment]
Provide the JSON from which the report can be generated.

**Comment by Blackbaud-JagjeetChadha** [comment]
@damianszczepanik - I think Json file is not getting created now. Does anyone faced same issue recently?

In the Gem file I have below dependencies:
gem 'selenium-webdriver', '= 3.141.0'
gem 'rspec'
gem 'rake'
gem 'builder'
gem 'cucumber', '2.99.0'
gem 'gherkin'
gem 'bundler'
gem 'pdf-reader'
gem 'yomu'
gem 'watir-ng', '2.1.1'
# gem 'webdrivers', "~> 3.0"

And in the folder I can see all the files except Json.
- ant-contrib-1.0b3.jar
- build.xml
- etap-merged.exec
- formatted_CP10.html
- jacocoant.jar
- mergedata.exec
- moveautomationresults
- performanceResults
- resultsBackup
- sonar-ant-task-2.2.jar

Can you please help me with this?
