### ISSUE TITLE
MismatchedInputException: No content to map due to end-of-input 0bytes Json File

### ISSUE THREAD

**Issue by mjdavies** [jenkinsci/cucumber-reports-plugin#322]
Hi there

We're suddenly getting the error message below when we're trying to create the cucumber.json file.  It happens nearly all of the time, but not %100 all the time, it didn't happen early this morning for instance.

We haven't changed the test code, or the versions of anything, so as it's happening sporadically I'm leaning towards a resource issue or something?

Has anyone seen this happen before or have any idea how to get around this?

`net.masterthought.cucumber.ValidationException: File '/var/jenkins_home/jobs/job_name/builds/487/cucumber-html-reports/.cache/cucumber.json' is not proper Cucumber report!
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:99)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:71)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:404)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:324)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1844)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (InputStreamReader); line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4145)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3049)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:93)
	... 14 more`

The cucumber.json file is completely empty, 0bytes.

Any help or tips are greatly appreciated.

**Comment by mjdavies** [comment]
I've tried using the suggestion here

https://github.com/jenkinsci/cucumber-reports-plugin/issues/312#issuecomment-482865428

So far 2 runs, both complete with a cucumber report.

I'll check again tomorrow when the server is a bit more busy, but that may well have sorted it.

**Comment by mjdavies** [comment]
Ok, our IE test failed and I think I've tracked down the issue

Something is timing out after 30 minutes

**Comment by mjdavies** [comment]
Is there a timeout option within the plugin itself, or one I can override?  The timeout may be happening elsewhere though, this is a laugh

**Comment by mjdavies** [comment]
Ok, found it, there's a 30 minute timeout step setup in the build environment.

Apologies for wasting anyone's time.

**Comment by lalithkumar97** [comment]
> Ok, found it, there's a 30 minute timeout step setup in the build environment.
> 
> Apologies for wasting anyone's time.

@mjdavies Even I'm facing the same issue can please tell where exactly did you update this??
I looked for timeout variable in build environment but was not able to find it
