### ISSUE TITLE
net.masterthought.cucumber.ValidationException: File

### ISSUE THREAD

**Issue by mahmoudshuaibi** [jenkinsci/cucumber-reports-plugin#347]
PLEASE HELP!
**Cucumber report plugin been updated on Jenkins to 5.0.2 version, and after the update i got the following Error, how ever i have updated my xml net.masterthought - cucumber-reporting to 5.0.2 and i changed the path to in my runner class i still have the same issue following my runner class code**

plugin = {"pretty","html:target/HTML", "json:target/cucumber.json"},//json:target/cucumber-reports/cucumber.json
        features = "src/test/resources/features",
        glue = "steps",
        tags = {"@rccSmokeTests"},
        dryRun = false

**Error on jenkins**
Error
Something went wrong with project CaseCollectionSmoke, build 67

net.masterthought.cucumber.ValidationException: File 'C:\Program Files (x86)\Jenkins\jobs\CaseCollectionSmoke\builds\67\cucumber-html-reports\.cache\target\cucumber.json' is not proper Cucumber report!
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:101)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:73)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:432)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:346)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1878)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:427)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (InputStreamReader); line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4344)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4189)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3218)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:95)
	... 14 more
Trying to generate report from following files. Make sure they are valid cucumber report files:
 C:\Program Files (x86)\Jenkins\jobs\CaseCollectionSmoke\builds\67\cucumber-html-reports\.cache\target\cucumber.json

**Comment by damianszczepanik** [comment]
Can you attach JSON file with report?

**Comment by Tuman829** [comment]
I am running into this same issue, in my case both of the report files are empty. 
However, I suspect that this a cucumber or Jenkins issue, not a plugin issue
