### ISSUE TITLE
Getting JsonParseException: Unexpected character ('/' (code 47)): error

### ISSUE THREAD

**Issue by Automationrode** [jenkinsci/cucumber-reports-plugin#349]
I am trying to generate json report using jenkins pipeline and I am getting the following error. 
It was working earlier and now from past few days I am facing this issue. 
I did cat report1.json and cat report2.json and tried to generate html from the online html page builder and I can see both the reports. But when I try with cucumber report plugin it is throwing error.

This is in the jenkins stage 
stage('Generating reports') {
            steps{
                script{
                    dir("/go/src/test-automation/testing-integration/API") {
                    sh "cp /go/src/test-automation/testing-integration/API_new/report1.json /go/src/test-automation/testing-integration/API"
                    cucumber fileIncludePattern: '**/*.json', sortingMethod: 'ALPHABETICAL', ignoreFailedTests: false, buildStatus: 'failed'
                    }
                }
            }
        }

`net.masterthought.cucumber.ValidationException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('/' (code 47)): Expected space separating root-level values
 at [Source: (InputStreamReader); line: 1, column: 6]
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:102)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:71)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:324)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:248)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('/' (code 47)): Expected space separating root-level values
 at [Source: (InputStreamReader); line: 1, column: 6]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:591)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportMissingRootWS(ParserMinimalBase.java:638)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._verifyRootSpace(ReaderBasedJsonParser.java:1664)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parsePosNumber(ReaderBasedJsonParser.java:1307)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:754)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3049)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:93)
	... 14 more`

Trying to generate report from following files. Make sure they are valid cucumber report files:
           `/var/jenkins_home/jobs/automation-test/jobs/testing-integration/builds/143/cucumber-html-reports/.cache/report1.json`
           `/var/jenkins_home/jobs/automation-test/jobs/testing-integration/builds/143/cucumber-html-reports/.cache/report2.json`

**Comment by damianszczepanik** [comment]
JSON you are trying to plugin is not cucumber report file
