### ISSUE TITLE
ERROR: Build step failed with exception when using Cucumber Reports version 5.4.0

### ISSUE THREAD

**Issue by zhidongnick** [jenkinsci/cucumber-reports-plugin#387]
From Jenkins 2.272 to 2.275, we are always encountering the following errors. Please investigate.

Cucumber HTML report /var/lib/jenkins/workspace/WOM_UI_BDD/wom_bdd/reports/wom-cucumber-report-chrome_202101180547.html generated successfully 👍
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level /var/lib/jenkins/workspace/WOM_UI_BDD/wom_bdd/reports to /var/lib/jenkins/jobs/WOM_UI_BDD/htmlreports/HTML_20Report
[CucumberReport] Using Cucumber Reports version 5.4.0
ERROR: Build step failed with exception
java.lang.IllegalStateException
	at org.objectweb.asm.tree.analysis.BasicInterpreter.<init>(BasicInterpreter.java:66)
	at org.parboiled.transform.RuleMethodInterpreter.<init>(RuleMethodInterpreter.java:42)
	at org.parboiled.transform.InstructionGraphCreator.process(InstructionGraphCreator.java:41)
	at org.parboiled.transform.ParserTransformer.runMethodTransformers(ParserTransformer.java:62)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:45)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:39)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
Caused: java.lang.RuntimeException: Error creating extended parser class: null
	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
	at org.jenkinsci.plugins.tokenmacro.Parser.process(Parser.java:80)
	at org.jenkinsci.plugins.tokenmacro.Parser.process(Parser.java:74)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expand(TokenMacro.java:199)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:237)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:207)
	at net.masterthought.jenkins.CucumberReportPublisher.evaluateMacro(CucumberReportPublisher.java:607)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:398)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:369)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:752)
	at hudson.model.Build$BuildExecution.post2(Build.java:177)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:697)
	at hudson.model.Run.execute(Run.java:1932)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Cucumber reports' marked build as failure

**Comment by ZyanKLee** [comment]
You are not alone, I got the same issue with one of our projects.

**Comment by damianszczepanik** [comment]
Try update tokenmacro plugin

**Comment by mattoolprawin** [comment]
Runner class should contain the following 
plugin= {"pretty","html:target/cucumber-html-reports","json:target/cucumber.json"}

then while adding post-build action to add cucumber reports option in jenkins

1. keep the JSON Reports Path null
2. File Include Pattern as **/cucumber.json
3. save it.

This will fix the issue "Caused: java.lang.RuntimeException: Error creating extended parser class: null" and cucumber report will be displayed in jenkins
