### ISSUE TITLE
Cucumber failed to generate report in Jenkins

### ISSUE THREAD

**Issue by lalithkumar97** [jenkinsci/cucumber-reports-plugin#417]
we are getting this below error while executing test cases from jenkins.
- Execution is happening but at the end it is failing to generate report 
- It happens only for iOS device testing but not for windows application.
- And this happens if we include more than 20 test cases, if the test cases are less than 20 it works fine (only for iOS device testing)
- The cucumber.json file is completely empty.

Something went wrong with project UI_POS_IOS_ONLINE_STAGE, build 96

net.masterthought.cucumber.ValidationException: File '/var/lib/jenkins/jobs/ART_Automation_Pipeline/jobs/ART_UI_Pipeline/jobs/UI_POS_IOS_ONLINE_STAGE/builds/96/cucumber-html-reports/.cache/cucumber-usage.json' is not proper Cucumber report!
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:101)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:73)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:432)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:346)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (InputStreamReader); line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4344)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4189)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3218)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:95)
	... 14 more
Trying to generate report from following files. Make sure they are valid cucumber report files:
 /var/lib/jenkins/jobs/ART_Automation_Pipeline/jobs/ART_UI_Pipeline/jobs/UI_POS_IOS_ONLINE_STAGE/builds/96/cucumber-html-reports/.cache/cucumber-usage.json
 /var/lib/jenkins/jobs/ART_Automation_Pipeline/jobs/ART_UI_Pipeline/jobs/UI_POS_IOS_ONLINE_STAGE/builds/96/cucumber-html-reports/.cache/cucumber.json
   
Any help or tips will be really helpful.

**Comment by damianszczepanik** [comment]
Attach cucumber-usage.json

**Comment by lalithkumar97** [comment]
Thanks for you response,

After the execution cucumber-usage.json and cucumber.json which is generated has no data and It is 0 bytes and that is what I mentioned in my problem statement.

[cucumber-usage.json.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/9038990/cucumber-usage.json.zip)

**Comment by damianszczepanik** [comment]
Attached file is empty - that's the reason
