### ISSUE TITLE
Cucumber Reports are not generated in Jenkins 

### ISSUE THREAD

**Issue by ravichandrasurabhi** [jenkinsci/cucumber-reports-plugin#442]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

[INFO] ------------------------------------------------------------------------ 
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:03 min
[INFO] Finished at: 2023-07-31T14:12:44Z
[INFO] ------------------------------------------------------------------------
Waiting for Jenkins to finish collecting data
[JENKINS] Archiving /home to SNAPSHOT.pom
channel stopped
[CucumberReport] Using Cucumber Reports version 5.5.0
[CucumberReport] JSON report directory is ""
[CucumberReport] Copied 1 json files from workspace "/home" to reports directory "/cucumber-html-reports/.cache"
[CucumberReport] Copied 8 properties files from workspace "/home/" to reports directory "/cucumber-html-reports/.cache"
[CucumberReport] Processing 1 json files:
[CucumberReport] cucumber-html-reports/.cache/target/cucumberReport.json
ERROR: Build step failed with exception
org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'templates/generators/errorpage.vm'
      at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474)
      at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
      at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
      at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1514)
      at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:373)
      at net.masterthought.cucumber.generators.AbstractPage.generateReport(AbstractPage.java:81)
      at net.masterthought.cucumber.generators.AbstractPage.generatePage(AbstractPage.java:66)
      at net.masterthought.cucumber.ReportBuilder.generateErrorPage(ReportBuilder.java:230)
      at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:109)
      at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:470)
      at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:369)
      at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
      at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
      at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
      at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
      at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:752)
      at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1072)
      at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:697)
      at hudson.model.Run.execute(Run.java:1932)
      at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
      at hudson.model.ResourceController.execute(ResourceController.java:97)
      at hudson.model.Executor.run(Executor.java:429)
Build step 'Cucumber reports' marked build as failure 

### Expected Results

Cucumber Reports

### Actual Results

Build step 'Cucumber reports' marked build as failure

**Comment by ravichandrasurabhi** [comment]
@damianszczepanik - Please check

**Comment by damianszczepanik** [comment]
I believe the problem is how are you trying to run the report. Problem with flassoath or similar. Not related to the pkugin
