### ISSUE TITLE
Cucumber report Jenkins plugin fails with the exception net.masterthought.cucumber.ValidationException  ….. is not a valid Cucumber report! when there is a value in the "argument" field

### ISSUE THREAD

**Issue by rmathews2** [jenkinsci/cucumber-reports-plugin#443]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

windows, mac

### Reproduction steps

Framework used: Webdriverio

Below are the dependencies used :
"@cucumber/cucumber": "^7.2.1",
 "@wdio/cucumber-framework": "^6.11.1",
"cucumber-html-reporter": "^5.3.0",
"multiple-cucumber-html-reporter": "^1.18.0",
"wdio-cucumber-parallel-execution": "^3.6.15",
"wdio-cucumberjs-json-reporter": "^2.0.2",

cucumber-jenkins-plugin : [5.7.3](https://plugins.jenkins.io/cucumber-reports)

Webdriverio version: "@wdio/cli": "^7.19.7",

Description:
Run a jenkins job for few webDriverIO tests. Verify if cucumber reports are generated for the tests. 
This issue occurs when there's a value in the "arguments" field within Elements (Scenario) > Steps
Any value in the "arguments" field causes the crash.
In Feature file this would translate to 
```
When I paste "html" to Notes: 
"""
   <span style=\"text-decoration: underline line-through\">AAAAA</span>
"""
```

Example of a cucumber report Element > Steps : 
```
{
    "arguments": [
        "<span style=\"text-decoration: underline line-through\">AAAAA</span>"
    ],
    "keyword": "When",
    "name": "I paste \"html\" to Notes:",
    "result": {
        "status": "passed",
        "duration": 134000000
    },
    "match": {
        "location": "can not be determined with webdriver.io"
    }
},
```

It crashes with the error "net.masterthought.cucumber.ValidationException: File '/mnt/jenkins/builds/Test/480/cucumber-html-reports/.cache/target/webdriverio-test-reports/combined-modified-reports/combined-report.json' is not a valid Cucumber report!"

### Expected Results

Cucumber report to be generated as usual

### Actual Results

Cucumber report generation is not happening, throws the below error: 

Stacktrace:
net.masterthought.cucumber.ValidationException: File '/mnt/jenkins/builds/Test/480/cucumber-html-reports/.cache/target/webdriverio-test-reports/combined-modified-reports/combined-report.json' is not a valid Cucumber report!
at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:104)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:72)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:97)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:563)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:434)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by damianszczepanik** [comment]
Attach JSON file

**Comment by rmathews2** [comment]
[error-cucumber-report.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/12255280/error-cucumber-report.txt)

**Comment by damianszczepanik** [comment]
This is not valid JSON syntax

```
                        "arguments": [
                            "content to paste"
                        ],
```
