### ISSUE TITLE
Plugin fails to read json report

### ISSUE THREAD

**Issue by Re4zOon** [jenkinsci/cucumber-reports-plugin#485]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.462.2
OS: Linux - 3.10.0-1160.119.1.el7.x86_64
Java: 17.0.12 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
analysis-model-api:12.7.0
ansicolor:1.0.4
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.4-118.v199115451c4d
asm-api:9.7-33.v4d23ef79fcc8
authentication-tokens:1.119.v50285141b_7e1
authorize-project:1.7.2
blueocean:1.27.16
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.27.16
blueocean-commons:1.27.16
blueocean-config:1.27.16
blueocean-core-js:1.27.16
blueocean-dashboard:1.27.16
blueocean-display-url:2.4.3
blueocean-events:1.27.16
blueocean-git-pipeline:1.27.16
blueocean-github-pipeline:1.27.16
blueocean-i18n:1.27.16
blueocean-jira:1.27.16
blueocean-jwt:1.27.16
blueocean-personalization:1.27.16
blueocean-pipeline-api-impl:1.27.16
blueocean-pipeline-editor:1.27.16
blueocean-pipeline-scm-api:1.27.16
blueocean-rest:1.27.16
blueocean-rest-impl:1.27.16
blueocean-web:1.27.16
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
branch-api:2.1178.v969d9eb_c728e
build-name-setter:2.4.3
build-timeout:1.33
build-user-vars-plugin:176.vb_9c7907fd524
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.1
chucknorris:159.vdfe649cb_9c37
cloud-stats:336.v788e4055508b_
cloudbees-bitbucket-branch-source:888.v8e6d479a_1730
cloudbees-folder:6.951.v5f91d88d76b_b_
command-launcher:115.vd8b_301cc15d0
commons-compress-api:1.26.1-2
commons-lang3-api:3.17.0-84.vb_b_938040b_078
commons-text-api:1.12.0-129.v99a_50df237f7
conditional-buildstep:1.4.3
config-file-provider:978.v8e85886ffdc4
configurationslicing:548.ve92d48e66b_f8
copyartifact:749.vfb_dca_a_9b_6549
coverage:1.16.1
credentials:1378.v81ef4269d764
credentials-binding:681.vf91669a_32e45
cucumber-reports:5.8.1
dark-theme:479.v661b_1b_911c01
data-tables-api:2.1.6-1
declarative-pipeline-migration-assistant:1.6.4
declarative-pipeline-migration-assistant-api:1.6.4
display-url-api:2.204.vf6fddd8a_8b_e9
docker-commons:443.v921729d5611d
docker-custom-build-environment:1.7.3
docker-java-api:3.3.6-90.ve7c5c7535ddd
docker-workflow:580.vc0c340686b_54
dtkit-api:3.0.2
durable-task:577.v2a_8a_4b_7c0247
echarts-api:5.5.1-1
eddsa-api:0.3.0-4.v84c6f0f4969e
email-ext:1814.v404722f34263
envinject:2.919.v009a_a_1067cd0
envinject-api:1.199.v3ce31253ed13
extended-choice-parameter:382.v5697b_32134e8
extensible-choice-parameter:1.8.1
external-monitor-job:215.v2e88e894db_f8
favorite:2.221.v19ca_666b_62f5
font-awesome-api:6.6.0-2
forensics-api:2.6.0
git:5.5.1
git-client:5.0.0
git-server:126.v0d945d8d2b_39
github:1.40.0
github-api:1.321-468.v6a_9f5f2d5a_7e
github-branch-source:1797.v86fdb_4d57d43
gitlab-plugin:1.8.1
gson-api:2.11.0-41.v019fcf6125dc
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
htmlpublisher:1.36
instance-identity:185.v303dc7c645f9
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jacoco:3.3.6
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:280.v050b_5c849f69
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jdk-tool:80.v8a_dee33ed6f0
jenkins-design-language:1.27.16
jersey2-api:2.44-151.v6df377fff741
jira:3.13
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
job-dsl:1.89
jobConfigHistory:1264.v054b_c928547e
joda-time-api:2.13.0-85.vb_64d1c2921f1
jquery:1.12.4-1
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-41.v94e11e6de726
json-path-api:2.9.0-58.v62e3e85b_a_655
junit:1300.v03d9d8a_cf1fb_
ldap:725.v3cb_b_711b_1a_ef
lockable-resources:1310.v99ca_947ed698
mailer:472.vf7c289a_4b_420
mapdb-api:1.0.9-40.v58107308b_7a_7
matrix-auth:3.2.2
matrix-combinations-parameter:1.3.3
matrix-project:832.va_66e270d2946
maven-plugin:3.23
metrics:4.2.21-451.vd51df8df52ec
mina-sshd-api-common:2.13.2-125.v200281b_61d59
mina-sshd-api-core:2.13.2-125.v200281b_61d59
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
pam-auth:1.11
parameterized-scheduler:277.v61a_4b_a_49a_c5c
parameterized-trigger:806.vf6fff3e28c3e
performance:962.v95a_4913d332e
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-github-lib:61.v629f2cc41d83
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-graph-view:340.v28cecee8b_25f
pipeline-groovy-lib:730.ve57b_34648c63
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-definition:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-extensions:2.2214.vb_b_34b_2ea_9b_83
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2214.vb_b_34b_2ea_9b_83
pipeline-stage-view:2.34
pipeline-utility-steps:2.17.0
plain-credentials:183.va_de8f1dd5a_2b_
plugin-usage-plugin:4.5
plugin-util-api:5.1.0
postbuild-task:1.9
prism-api:1.29.0-17
publish-over:0.22
pubsub-light:1.18
rebuild:332.va_1ee476d8f6d
resource-disposer:0.23
role-strategy:743.v142ea_b_d5f1d3
run-condition:1.7
scm-api:696.v778d637b_a_762
script-security:1362.v67dc1f0e1b_b_3
slack:741.v00f9591c586d
sloccount:1.27
snakeyaml-api:2.3-123.v13484c65210a_
sse-gateway:1.27
ssh-agent:376.v8933585c69d3
ssh-credentials:343.v884f71d78167
ssh-slaves:2.973.v0fa_8c0dea_f9f
ssh-steps:2.0.68.va_d21a_12a_6476
sshd:3.330.vc866a_8389b_58
structs:338.v848422169819
test-results-analyzer:0.4.1
theme-manager:262.vc57ee4a_eda_5d
throttle-concurrents:2.14
token-macro:400.v35420b_922dcb_
trilead-api:2.147.vb_73cc728a_32e
uno-choice:2.8.3
variant:60.v7290fc0eb_b_cd
view-job-filters:382.vdf2d5e3f02f0
warnings-ng:11.7.0
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1336.vee415d95c521
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3964.v0767b_4b_a_0b_fa_
workflow-durable-task-step:1371.vb_7cec8f3b_95e
workflow-job:1436.vfa_244484591f
workflow-multibranch:795.ve0cb_1f45ca_9a_
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:678.v3ee58b_469476
workflow-support:926.v9f4f9b_b_98c19
ws-cleanup:0.46
 ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins is running docker LTS, agents are on Centos7

### Reproduction steps

Run a cucumber test, let the plugin read the json.

### Expected Results

Json can be read

### Actual Results

The propertiesConfiguration class seems to be missing:
```
org.apache.commons.configuration2.ex.ConfigurationRuntimeException: java.lang.ClassNotFoundException: org.apache.commons.configuration2.PropertiesConfiguration
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.beanutils.BeanHelper.fetchBeanClass(BeanHelper.java:413)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.beanutils.BeanHelper.createBeanCreationContext(BeanHelper.java:461)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.beanutils.BeanHelper.createBean(BeanHelper.java:339)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.beanutils.BeanHelper.createBean(BeanHelper.java:357)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.beanutils.BeanHelper.createBean(BeanHelper.java:369)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.builder.BasicConfigurationBuilder.createResultInstance(BasicConfigurationBuilder.java:360)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.builder.BasicConfigurationBuilder.createResult(BasicConfigurationBuilder.java:337)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.builder.BasicConfigurationBuilder.getConfiguration(BasicConfigurationBuilder.java:233)
	at PluginClassLoader for cucumber-reports//net.masterthought.cucumber.ReportParser.processClassificationFile(ReportParser.java:143)
	at PluginClassLoader for cucumber-reports//net.masterthought.cucumber.ReportParser.parseClassificationsFiles(ReportParser.java:132)
	at PluginClassLoader for cucumber-reports//net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:94)
	at PluginClassLoader for cucumber-reports//net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:563)
	at PluginClassLoader for cucumber-reports//net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:434)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
	at hudson.model.Build$BuildExecution.post2(Build.java:179)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:711)
	at hudson.model.Run.execute(Run.java:1917)
	at PluginClassLoader for matrix-project//hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:446)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.configuration2.PropertiesConfiguration
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at Jenkins Main ClassLoader//org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:511)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at PluginClassLoader for cucumber-reports//org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:532)
	at PluginClassLoader for cucumber-reports//org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:578)
	at PluginClassLoader for cucumber-reports//org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:561)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.beanutils.BeanHelper.loadClass(BeanHelper.java:382)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.beanutils.BeanHelper.fetchBeanClass(BeanHelper.java:411)
	... 23 more

Trying to generate report from following files. Make sure they are valid cucumber report files:
asdasd.json
```

### Anything else?

The workflow works fine with version 5.8.1, not sure what the breaking change could be.

**Comment by Re4zOon** [comment]
If it helps, the content of the properties file:
```
environment:stuff
ruby:ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
cucumber:9.2.0
chromeDriver:ChromeDriver 129.0.6668.58 (81a06fb873a9b386848719cf9f93e59579fb5d4b-refs/branch-heads/6668@{#1318})
browser:
```

**Comment by nicodn** [comment]
We're seeing something similar after upgrading to 5.8.3

We also use property files...

Our error logs include: `[CucumberReport] Missing report result - report was not successfully completed`

Downgrading back to 5.8.1 solved the issue.

**Comment by Re4zOon** [comment]
> We're seeing something similar after upgrading to 5.8.3
> 
> We also use property files...
> 
> Our error logs include: `[CucumberReport] Missing report result - report was not successfully completed`
> 
> Downgrading back to 5.8.1 solved the issue.

Yes, thats the same issue, I just went a level deeper :)

**Comment by damianszczepanik** [comment]
asdasd.json file is not a valid JSON file

**Comment by Re4zOon** [comment]
> asdasd.json file is not a valid JSON file

It is, according to 5.3.1.
Only the updated plugin fails to parse it.

Also the JSON is generated by maven (I think).

**Comment by damianszczepanik** [comment]
`asdasd.json` does not look like a valid JSON file, rather some temp file - check it out

**Comment by Re4zOon** [comment]
The JSON file is created by cucumber, that's what the report plugin reads.
5.8.1 works fine, 5.8.3 fails. How can the JSON be the problem, if that doesn't change?

**Comment by damianszczepanik** [comment]
Attach that file

**Comment by damianszczepanik** [comment]
Attach the JSON report

**Comment by seittema** [comment]
@damianszczepanik  - Sorry for the delay - here is the report I think you need which fails with the newer version of the p[regression.apis.index.get.json](https://github.com/user-attachments/files/17721728/regression.apis.index.get.json)
lugin -

**Comment by damianszczepanik** [comment]
JSON file is valid so this is problem with your local configuration

**Comment by Re4zOon** [comment]
> JSON file is valid so this is problem with your local configuration

What configuration?
Please let us know what could break the plugin between two versions, which configuration changed.

**Comment by seittema** [comment]
> JSON file is valid so this is problem with your local configuration

@damianszczepanik - What configuration are you referencing? And what in the configuration would cause this? We haven't changed any configuration on the plugin or the jenkins job and upgrading the plugin to 5.8.3 breaks the reports we have been running for months, and downgrading the plugin to 5.8.1 it suddenly works again.  

```
org.apache.commons.configuration2.ex.ConfigurationRuntimeException: java.lang.ClassNotFoundException: org.apache.commons.configuration2.PropertiesConfiguration
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.beanutils.BeanHelper.fetchBeanClass(BeanHelper.java:413)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.beanutils.BeanHelper.createBeanCreationContext(BeanHelper.java:461)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.beanutils.BeanHelper.createBean(BeanHelper.java:339)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.beanutils.BeanHelper.createBean(BeanHelper.java:357)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.beanutils.BeanHelper.createBean(BeanHelper.java:369)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.builder.BasicConfigurationBuilder.createResultInstance(BasicConfigurationBuilder.java:360)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.builder.BasicConfigurationBuilder.createResult(BasicConfigurationBuilder.java:337)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.builder.BasicConfigurationBuilder.getConfiguration(BasicConfigurationBuilder.java:233)
	at PluginClassLoader for cucumber-reports//net.masterthought.cucumber.ReportParser.processClassificationFile(ReportParser.java:143)
	at PluginClassLoader for cucumber-reports//net.masterthought.cucumber.ReportParser.parseClassificationsFiles(ReportParser.java:132)
	at PluginClassLoader for cucumber-reports//net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:94)
	at PluginClassLoader for cucumber-reports//net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:563)
	at PluginClassLoader for cucumber-reports//net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:434)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at PluginClassLoader for workflow-basic-steps//org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at PluginClassLoader for workflow-basic-steps//org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at PluginClassLoader for workflow-step-api//org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.configuration2.PropertiesConfiguration
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at Jenkins Main ClassLoader//org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:511)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at PluginClassLoader for cucumber-reports//org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:532)
	at PluginClassLoader for cucumber-reports//org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:578)
	at PluginClassLoader for cucumber-reports//org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:561)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.beanutils.BeanHelper.loadClass(BeanHelper.java:382)
	at PluginClassLoader for cucumber-reports//org.apache.commons.configuration2.beanutils.BeanHelper.fetchBeanClass(BeanHelper.java:411)
	... 21 more
```

**Comment by damianszczepanik** [comment]
There might be a lack compatibility between new plugin version and the Jenkins you are using. I'm testing against most recent LTS version before new version is published

**Comment by damianszczepanik** [comment]
Once Jenkins is upgraded also several plugins must be updated as well to keep everything up and running

**Comment by Re4zOon** [comment]
@damianszczepanik our jenkins always runs on LTS (updates itself daily).

**Comment by k4m4rov12** [comment]
After upgrading to 5.8.5 the issue still persists. 
The error is the same: `[CucumberReport] Missing report result - report was not successfully completed`
Version 5.8.1 can process the JSON file.

Jenkins runs on LTS, plugins were updated.

**Comment by delijo** [comment]
This is still an issue with Cucumber Report plugin v5.10.2 on Jenkins LTS 2.528.3 as soon as we use the classificationsFilePattern option to point a properties file.

The error log is the same:
`java.lang.ClassNotFoundException: org$apache$commons$configuration2$PropertiesConfiguration`

It really looks like a missing dependency.

**Comment by simplyajith** [comment]
Hi, we found a workaround. Inject the properties file as environment variable and look for classification in cucumber plugin, click on add and then update the individual properties present in properties file as classification. This works, we should not update anything on classification file pattern.

**Comment by delijo** [comment]
Not sure if this is similar to your workaround as I am not sure to understand well how you pass the properties values with your method.
My current workaround is to read the properties file and convert it to the list format expected by the `classifications` parameter:
`classifications: readProperties(file: 'reports/environment.properties').collect {entry -> ['key': entry.key, 'value': entry.value]}`
This is what I put in place to have the minimum manual maintenance.
