### ISSUE TITLE
Cucumber-JVM Report  Error

### ISSUE THREAD

**Issue by peppeweb** [jenkinsci/cucumber-reports-plugin#94]
Dear all,

All of a sudden the plugin is giving an error and I cannot explain where is the issue and how to solve it.
We run 3.1.0 and i tried to downgrade to 3.0

Any  clues on how to fix it?
Many Thanks

The error :

+1: net.masterthought.cucumber.ValidationException: File '//jenkins/jobs/XXX/builds/245/build-info.json' is not proper Cucumber report!
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:87)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:58)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:76)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:129)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:79)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1067)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:544)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of net.masterthought.cucumber.json.Feature[] out of START_OBJECT token
 at [Source: java.io.InputStreamReader@634fdaa9; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.handleNonArray(ObjectArrayDeserializer.java:275)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:179)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2878)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:81)
	... 14 more
Trying to generate report from following files. Make sure they are valid cucumber report files:
           xxx/builds/245/build-info.json
       xxx/builds/245/cucumber.json

**Comment by damianszczepanik** [comment]
It says that the report is not valid. Attach json file

**Comment by peppeweb** [comment]
Hi Damian,

It's company data, i would prefer to not publish it, and i think that if i scrubble it then maybe there will be not enough info to understand the problem.

Are there common errors, things to check in the json files?
The Json is correctly formatted.

**Comment by peppeweb** [comment]
Something more, the plugin is complaining about the build.json file. 
I'm comparing now the content and one thing that is different is the order of the Element in the tree.

![comparison buildjson](https://cloud.githubusercontent.com/assets/4136068/19959668/a591e89e-a1a8-11e6-8b22-7622d6c78fac.png)

**Comment by peppeweb** [comment]
Something more, the plugin is complaining about the build.json file. 
I'm comparing now the content and one thing that is different is the order of the Element in the tree.
![comparison buildjson](https://cloud.githubusercontent.com/assets/4136068/19959685/c48ae23c-a1a8-11e6-82b0-8d0b845b84c4.png)

**Comment by peppeweb** [comment]
Also I see that in the failing one there is one json node more .

vcs
0
revision : "ccbeda7beafbef692ac9e2e35c5898580684d39b"
url : "ccbeda7beafbef692ac9e2e35c5898580684d39b"

**Comment by damianszczepanik** [comment]
Need whole file

**Comment by peppeweb** [comment]
Here we go, and thanks for helping.
Giuseppe
[scrubbed_failing_build-info.json.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/569102/scrubbed_failing_build-info.json.txt)

**Comment by damianszczepanik** [comment]
Doesn't look like json report. What library did you use to generate it?

**Comment by peppeweb** [comment]
I use maven to generate the build, the other file generated is the cucumber.json.

**Comment by peppeweb** [comment]
Hi Damian, 

This is the cucumber-report json, I had to scrub this as well .
[failing_cucumber_scrubbed.json.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/575016/failing_cucumber_scrubbed.json.txt)

**Comment by damianszczepanik** [comment]
OK, so the reason why your build fails is that you are trying to parse files that are not proper cucumber reports. One of the attached is proper cucumber report while other doesn't. So try to use include and exclude rules to filter out reports you really want to parse.
